### ISSUE TITLE
parallel training 

### ISSUE THREAD

**Issue by ataha24** [afids/afids-CNN#6]
training is running for all afids at the same time. Perhaps enable some adaptive way so that it is not starting more training instances than resources provided

**Comment by tkkuehn** [comment]
The key constraint here is to know ahead of time what kind of resources we need. Without any changes, you can limit the number of cores you're requesting on SLURM or that snakemake uses (with `--cores {num_cores}`).

If we had some way to map the training parameters to the amount of memory each job will need, we could also use Snakemake to handle the resource management (i.e. not use more resources than the SLURM job provides)

**Comment by ataha24** [comment]
resolved in the latest dev branch and via kbatch submission
