### ISSUE TITLE
Possible bug in probability image generation

### ISSUE THREAD

**Issue by tkkuehn** [afids/afids-CNN#7]
https://github.com/afids/afids-CNN/blob/f2386cdb5d13b2022ba50ead71ad00a03c0ca08f/afids_cnn/train_workflow/workflow/Snakefile#L76

I was looking at this today and realized the probability images are being generated from the raw T1ws -- I think this should be from the AFID spheres instead (doesn't look like they get used anywhere). Possibly explains the slow convergence. @ataha24 can you take a look and confirm?

**Comment by ataha24** [comment]
Yes, correct. The  -sdt is creating the euclidean distance (ED) map which is what the network is predicting. To create the ED map, it is essentially taking in what I called a threshold image (binary image with a 1mm sphere of where the AFID is). Attached an example of my old notebook which shows the correct flow of images. 
![Screenshot 2023-09-12 at 10 36 18 AM (1)](https://github.com/afids/afids-CNN/assets/46094728/5c249792-cf96-4abe-82f8-d2964b20885f)
